routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Route::group(['middleware'=> 'auth','prefix' => '/admin', 'namespace' => 'App\Http\Controllers\Backend'], function() {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('/header', HeaderController::class);
    Route::resource('/what-we-do', WhatWeDoController::class);
    Route::resource('/our-work', OurWorkController::class);
    Route::resource('/who-we-are', WhoWeAreController::class);
    Route::resource('/question', QuestionController::class);
    Route::resource('/user-info', UserInfoController::class);
    Route::resource('/contact-us/price', ContactUsPriceController::class);
});



Route::group(['namespace' => 'App\Http\Controllers\Frontend'], function() {
    Route::get('/home', 'FrontDataController@home')->name('home');
    Route::get('/services', 'FrontDataController@services')->name('services');
    Route::get('/who-we-are', 'FrontDataController@whoWeAre')->name('who.we.are');
    Route::get('/our-work', 'FrontDataController@ourWork')->name('our.work');
    Route::get('/our-work/{id}', 'FrontDataController@ourWorkSingle')->name('our.work.single');
    Route::get('/contact-us/{level}', 'FrontDataController@contactUsView')->name('contact.us');
    Route::post('/contact-us', 'FrontDataController@contactUs')->name('contact.us.form');
});

app/Models/WhoWeAre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class WhoWeAre extends Model
{
    use HasFactory;

    protected $table = 'who_we_are';
    protected $fillable = [
        'path',
        'sub_description',
        'description',
    ];
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index(){
        return view('backend.dashboard.dashboard');
    }
}

app/Http/Controllers/Backend/WhoWeAreController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Hellper\Hellper;
use App\Http\Requests\WhoWeAre\CreateRequest;
use App\Http\Requests\WhoWeAre\EditRequest;
use App\Models\WhoWeAre;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class WhoWeAreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $whoWeAres = WhoWeAre::query()->orderBy('id', 'DESC')->paginate(10);
        return view('backend.dashboard.who-we-are.index',compact('whoWeAres'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('backend.dashboard.who-we-are.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateRequest $request)
    {
        DB::beginTransaction();
        $whoWeAre = new WhoWeAre();
        $path = storage_path('app' . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR . 'who-we-are' . DIRECTORY_SEPARATOR);
        $name =  Hellper::upload($request->image, $path);
        $image = "/storage/who-we-are/" . $name;
        $whoWeAre->path = $image;
        $whoWeAre->sub_description = $request->sub_description;
        $whoWeAre->description = $request->description;
        $whoWeAre->save();

        DB::commit();

        return redirect()->route('who-we-are.index')->with('message', 'Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit($id)
    {
        $whoWeAre = WhoWeAre::findOrFail($id);
        return view('backend.dashboard.who-we-are.edit',compact('whoWeAre'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(EditRequest $request, $id)
    {
        DB::beginTransaction();
        $whoWeAre = WhoWeAre::findOrFail($id);
        $whoWeAre->sub_description = $request->sub_description;
        $whoWeAre->description = $request->description;

        if ($request->image){
            $path = storage_path('app' . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR . 'who-we-are' . DIRECTORY_SEPARATOR);
            $PathForDelete = str_replace('/storage', '', $whoWeAre->path);
            Storage::delete('/public' . $PathForDelete);
            $name =  Hellper::upload($request->image, $path);
            $image = "/storage/who-we-are/" . $name;
            $whoWeAre->path = $image;
        }
        $whoWeAre->save();

        DB::commit();

        return redirect()->route('who-we-are.index')->with('message', 'Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $whoWeAre = WhoWeAre::findOrFail($id);
        $PathForDelete = str_replace('/storage', '', $whoWeAre->path);
        Storage::delete('/public' . $PathForDelete);
        $whoWeAre->delete();
        return redirect()->route('who-we-are.index')->with('message', 'Successfully');
    }
}

resources/views/backend/dashboard/who-we-are/create.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Create</title>
@endsection

@section('css')

@endsection



@section('dashboard')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Create</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/admin">Home</a></li>
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>


    <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">

                    <div class="col-md-12">
                        <div class="card card-default">
                            <div class="card-header">
                                <h3 class="card-title">Who We Are</h3>
                            </div>
                            <form action="{{route('who-we-are.store')}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="card-body row">
                                    <div class="form-group col-6">
                                        <label>Title</label>
                                        <input class="form-control" type="text" name="sub_description" placeholder="Slug title" value="{{ old('sub_description') }}">
                                    </div>
                                    <div class="form-group col-12">
                                        <label>Description</label>
                                        <textarea class="summernote" name="description">{{ old('description') }}</textarea>
                                    </div>
                                    <div class="form-group closest-img-files-one-custom">
                                        <div class="form-group col-12">
                                            <label for="exampleInputFile">Images</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file"  class="custom-file-input img-files-one-custom-input" name="image" >
                                                    <label class="custom-file-label" for="imgfilesOneCustom">Choose file</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="img-view-one-custom">

                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-success">Save</button>
                                </div>
                            </form>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
            </div>
        </section>
    <!-- /.content -->
</div>
@endsection

@section('js')

@endsection

resources/views/backend/dashboard/who-we-are/edit.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Edit</title>
@endsection

@section('css')
@endsection

@section('dashboard')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/admin">Home</a></li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">

                <div class="col-md-12">
                    <div class="card card-default">
                        <div class="card-header">
                            <h3 class="card-title">Who We Are</h3>
                        </div>
                        <form action="{{route('who-we-are.update', $whoWeAre->id)}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PATCH')
                            <div class="card-body row">
                                <div class="form-group col-6">
                                    <label>Sub description</label>
                                    <input class="form-control" type="text" name="sub_description" placeholder="Slug title" value="{{$whoWeAre->sub_description}}">
                                </div>
                                <div class="form-group col-12">
                                    <label>Description</label>
                                    <textarea class="summernote" name="description">{{$whoWeAre->description}}</textarea>
                                </div>
                                <div class="form-group closest-img-files-one-custom">
                                    <div class="form-group col-12">
                                        <label for="exampleInputFile">Images</label>
                                        <div class="input-group">
                                            <div class="custom-file">
                                                <input type="file"  class="custom-file-input img-files-one-custom-input" name="image" >
                                                <label class="custom-file-label" for="imgfilesOneCustom">Choose file</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="img-view-one-custom">

                                    </div>
                                    <div>
                                        <img src="{{asset($whoWeAre->path)}}" alt="" style="width: 30%;">
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </form>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

@section('js')

@endsection

resources/views/backend/dashboard/who-we-are/index.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Who We Are</title>
@endsection

@section('css')

    <style>
        .custom-scroll{
            display: block;
            height: 100px !important;
            overflow-y: scroll;
        }
    </style>
@endsection



@section('dashboard')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Who We Are</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/admin">Home</a></li>
                            <li class="breadcrumb-item active">Who We Are</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div>
{{--                                <a href="{{route('who-we-are.create')}}" class="btn btn-success" style="float: right; margin: 15px">Create</a>--}}
                            </div>
                        <!-- /.card-header -->
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Sub Description</th>
                                        <th>Description</th>
                                        <th>Access</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($whoWeAres as $item)
                                            <tr>
                                                <td style="width: 10%;"><img src="{{asset($item->path)}}" alt="" style="width: 100%;"></td>
                                                <td>{{$item->sub_description}}</td>
                                                <td>
                                                    <span class="custom-scroll">
                                                        {!! $item->description !!}
                                                    </span>
                                                </td>
                                                <td>
                                                    <div class="d-flex">
                                                        <a style="padding: 0px 5px;margin: 0px 8px;" href="{{ route("who-we-are.edit", $item->id) }}" class="btn btn-primary edit-access"><i  class="fas fa-edit" ></i></a>
{{--                                                        <form method="POST" action="{{ route("who-we-are.destroy" , $item->id) }}">--}}
{{--                                                            @csrf--}}
{{--                                                            @method('DELETE')--}}
{{--                                                            <a href="javascript:;" onclick="return confirm('Are you sure you want to delete this item?');">--}}
{{--                                                                <button type="submit" style="padding: 0px 5px;" class="ml-2 btn btn-danger" >--}}
{{--                                                                    <i class="fa fa-trash"></i>--}}
{{--                                                                </button>--}}
{{--                                                            </a>--}}
{{--                                                        </form>--}}
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach

                                    </tbody>
                                </table>
                            </div>
                            <div style="margin: 0 auto">
                                {{ $whoWeAres->links('pagination::bootstrap-4') }}
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('js')


@endsection